algoritmo "smnome"

var
a : caracter
inicio
escreval("Você é um giga chad?")
leia(a)
se (a = "sim") entao
   escreval("Posso ser seu servo?????")
   leia(a)
   se (a = "sim") entao
      escreval("Krlh vc é foda <3")
   senao
      escreval("Te odeio, me mate logo")
      escreval("(CLIQUE NO (X))")
   fimse
senao
   escreval("Te odeio, me mate logo")
   escreval("(CLIQUE NO (X))")
fimse
fimalgoritmo


